// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6pfvxjr87UsOEqRDtl86HgyOr0QLbeE',
    appId: '1:896404417484:web:ca710f1240d8bbe9ad4b69',
    messagingSenderId: '896404417484',
    projectId: 'projek-minggu111213',
    authDomain: 'projek-minggu111213.firebaseapp.com',
    storageBucket: 'projek-minggu111213.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd49JfSoI9IjB5foNgyvpYa9ev9Rfn9Jg',
    appId: '1:896404417484:android:b2147328878bb489ad4b69',
    messagingSenderId: '896404417484',
    projectId: 'projek-minggu111213',
    storageBucket: 'projek-minggu111213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2Qz96e6PGuxqyukCILBjXZkQkl-faTg',
    appId: '1:896404417484:ios:f9100a93b3d8b3cfad4b69',
    messagingSenderId: '896404417484',
    projectId: 'projek-minggu111213',
    storageBucket: 'projek-minggu111213.appspot.com',
    iosClientId: '896404417484-md3pc7llalrpvge6bn6m85hib9rpbolh.apps.googleusercontent.com',
    iosBundleId: 'com.example.minggu11Auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2Qz96e6PGuxqyukCILBjXZkQkl-faTg',
    appId: '1:896404417484:ios:f9100a93b3d8b3cfad4b69',
    messagingSenderId: '896404417484',
    projectId: 'projek-minggu111213',
    storageBucket: 'projek-minggu111213.appspot.com',
    iosClientId: '896404417484-md3pc7llalrpvge6bn6m85hib9rpbolh.apps.googleusercontent.com',
    iosBundleId: 'com.example.minggu11Auth',
  );
}
